

export enum Status {
    SUCCESS,
    CREATED,
    FAILED_VALIDATION,
    UN_AUTHORIZED,
    ERROR,
    NOT_FOUND,
    PRECONDITION_FAILED,
    SUCCESS_NO_CONTENT,
    FORBIDDEN,
    UNPROCESSABLE_ENTRY
}